### ISSUE TITLE
Mejoras al sitio y relevamiento de informacion

### ISSUE THREAD

**Issue by dakoo096** [PPROF1-2021/a3-g8-teamfire#20]
Añadir las meta etiquetas necesarias en la pagina de inicio, y corrobar que el sitio cumpla con los requisitos de funcionalidad responsive, no haya problema de conexion entre las paginas, ni problemas de cargas.
IMPORTANTE, corroborar que se cumpla con:
https://drive.google.com/drive/folders/1P73KEHnZNzEnYFE4o6DlhUCpZyb18MdR?usp=sharing

**Comment by vmsaravia** [comment]
Añadir las meta etiquetas necesarias en la pagina de inicio, y corrobar que el sitio cumpla con los requisitos de funcionalidad responsive, no haya problema de conexion entre las paginas, ni problemas de cargas.
